# Generated by Django 5.2.1 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
