# Generated by Django 5.2.1 on 2025-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='category_icons/')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('professional', 'Professional'), ('business', 'Business')], max_length=20)),
            ],
        ),
    ]
