# Generated by Django 5.2.1 on 2025-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaplatform',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='platform_icons/'),
        ),
    ]
