# Generated by Django 5.2.1 on 2025-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialmediaplatform_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaplatform',
            name='icon_image',
        ),
        migrations.AlterField(
            model_name='socialmediaplatform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='platform_icons/'),
        ),
    ]
