# Generated by Django 5.2.1 on 2025-06-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_socialmediaplatform_icon_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='data',
            new_name='platform_url',
        ),
    ]
