# Generated by Django 5.2.1 on 2025-07-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_data_socialmedialink_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
