# Generated by Django 5.2.1 on 2025-06-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='theme/backgrounds/')),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
