# Generated by Django 5.2.1 on 2025-06-25 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short, catchy title for the notification.', max_length=255)),
                ('message', models.TextField(help_text='The full content of the notification.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the recipient has read the notification.')),
                ('link', models.URLField(blank=True, help_text='An optional URL related to the notification (e.g., a link to a new feature).', max_length=500, null=True)),
                ('notification_type', models.CharField(choices=[('system', 'System Message'), ('announcement', 'Announcement'), ('alert', 'Alert'), ('info', 'Information'), ('custom', 'Custom')], default='system', help_text='Categorizes the type of notification.', max_length=20)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='The user (e.g., admin) who sent this notification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
